#!/usr/bin/env bash
# Script displays info about subdomains of a domain.

# Function to get subdomain info
get_subdomain_info() {
    domain="$1"
    subdomain="$2"
    dig_output=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION:/ {getline; print}')
    record_type=$(echo "$dig_output" | awk '{print $4}')
    destination=$(echo "$dig_output" | awk '{print $5}')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Main part
domain="$1"
subdomains=("www" "lb-01" "web-01" "web-02")

if [[ -z "$2" ]]; then
    for subdomain in "${subdomains[@]}"; do
        get_subdomain_info "$domain" "$subdomain"
    done
else
    subdomain="$2"
    get_subdomain_info "$domain" "$subdomain"
fi
