#!/usr/bin/env bash
# This script displays information about subdomains of a domain

domain="$1"
subdomain="$2"

# If subdomain is not provided, set default subdomains
if [ -z "$subdomain" ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
else
    subdomains=("$subdomain")
fi

# Loop through subdomains and display information
for sub in "${subdomains[@]}"; do
    dig_output=$(dig +short "$sub.$domain")
    record_type=$(dig +short "$sub.$domain" | awk 'NR==1{print $4}')
    echo "The subdomain $sub is a $record_type record and points to $dig_output"
done
