#!/usr/bin/env bash
# This script displays information about subdomains of a domain

display_dns_info() {
    domain="$1"
    subdomain="$2"

    # If subdomain is not provided, set default subdomains
    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    # Loop through subdomains and display information
    for sub in "${subdomains[@]}"; do
        dig_output=$(dig +short "$sub.$domain")
        record_type=$(dig +short "$sub.$domain" | awk 'NR==1{print $4}')
        echo "The subdomain $sub is a $record_type record and points to $dig_output"
    done
}

# Main function
main() {
    # Check if both domain and subdomain are provided
    if [ "$#" -eq 2 ]; then
        display_dns_info "$1" "$2"
    # Check if only domain is provided
    elif [ "$#" -eq 1 ]; then
        display_dns_info "$1"
    else
        echo "Usage: $0 <domain> [subdomain]"
        exit 1
    fi
}

# Execute main function with provided arguments
main "$@"
