#!/usr/bin/env bash
# This script installs Nginx and configures it to meet the requirements

# Updating package list and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Creating index.html with "Hello World!"
echo "Hello World!" > /var/www/html/index.html

# Restarting Nginx (no systemctl)
service nginx start
