#!/usr/bin/env bash
# This script installs Nginx and configures it to meet the requirements

apt-get -y update
apt-get -y install nginx
ufw allow  'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx restart
