#!/usr/bin/env bash
# This script installs Nginx and configures it to meet requirements

# Update package list
apt-get update -y

# Install Nginx
apt-get install nginx -y

# Ensure Nginx is listening on port 80
sed -i 's/\blisten 80;/listen 80 default_server;/g' /etc/nginx/sites-available/default

# Create index.html with "Hello World!"
echo "Hello World!" > /var/www/html/index.html

# Restart Nginx to apply changes
service nginx restart
