#!/usr/bin/env bash
# This script installs Nginx, configures a URL redirection, and restarts Nginx

sudo apt-get -y install nginx
echo "301 Moved Permanently" | sudo tee /usr/share/nginx/html/index.html
fill="location /redirect_me {\nrewrite ^/(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n}\n"
sudo sed -i "/# Only/ i $fill" /etc/nginx/sites-available/default
sudo service nginx restart
