#!/usr/bin/env bash
# This script configures the Nginx server to have a custom 404 page

apt-get -y update
apt-get -y install nginx
ufw allow "Nginx HTTP"

# Create a custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Configure Nginx to use the custom 404 page
sed -i '/^server {/a \\t\terror_page 404 /custom_404.html;' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart
