#!/usr/bin/env bash
# This script configures the Nginx server to have a custom 404 page

apt-get -y update
apt-get -y install nginx
ufw allow "Nginx HTTP"
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sed -i "46i error_page 404 /custom_404.html;" /etc/nginx/sites-available/default
sed -i "46i rewrite ^/redirect_me  permanent;" /etc/nginx/sites-available/default
service nginx restart
