#!/usr/bin/env bash
# Script configures Nginx so that its HTTP response contains a custom header

sudo apt-get -y update
sudo apt-get install -y nginx
sudo ufw allow "Nginx HTTP"
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sudo sed -i "/server_name _;/ a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo sed -i "/server_name _;/ a error_page 404 /custom_404.html;" /etc/nginx/sites-available/default
sudo sed -i "/server_name _;/ a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx restart
