#!/usr/bin/env bash
# Script configures Nginx so that its HTTP response contains a custom header

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
served_by="add_header X-Served-By \$hostname;\n"
sudo sed -i "21i $served_by" /etc/nginx/sites-available/default
sudo service nginx restart
