#!/usr/bin/env bash
# Installs and configures HAProxy on lb-01 server to distribute traffic to web-01 and web-02 using a round-robin algorithm.
# It also ensures that HAProxy can be managed via an init script.

# Update package lists and install HAProxy
apt-get -y update
apt-get install -y haproxy
#front-end listener
echo -e "\nfrontend Server\n\tbind *:80\n\tmode http\n\tdefault_backend My_Web_Servers\n\n" | sudo tee -a /etc/haproxy/haproxy.cfg
#back-end web severs
echo -e "backend My_Web_Servers\n\tbalance roundrobin\n\tserver web-01 100.25.15.192:80 check\n\tserver web-02 3.94.181.137:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
