#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but with a special output on the 9th iteration

counter=0

while [ $counter -lt 10 ]; do
    # Checking if it is 9th iteration
    if [ $counter -eq 8 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi

    ((counter++))
done
