#!/usr/bin/env bash
# This script is displaying numbers from 1 to 20 with particular messages for certain iterations

counter=1

while [ $counter -le 20 ]; do
    # Using a case statement to display messages based on the iteration
    case $counter in
        4)
            echo -e "$counter\nbad luck from China"
            ;;
        9)
            echo -e "$counter\nbad luck from Japan"
            ;;
        17)
            echo -e "$counter\nbad luck from Italy"
            ;;
        *)
            echo $counter
            ;;
    esac

    ((counter++))
done
