#!/usr/bin/env bash
# This script is displaying the time for 12 hours and 59 minutes using a while loop.

# Initializing variables
hours="0"
minutes="1"

# Outer loop for hours
while [ $hours -lt 13 ]
do
    # Displaying the current hour
    echo "Hour: $hours"

    # Inner loop for minutes
    while [ $minutes -lt 60 ]
    do
        # Displaying the current minute
        echo "$minutes"
        # Incrementing the minute
        minutes=$((minutes+1))
    done

    # Resetting minutes for the next hour
    minutes="1"

    # Incrementing the hour
    hours=$((hours+1))
done
