#!/usr/bin/env bash
# This script is giving information about the school file

file_path="school"

# Checking if the file exists
if [ -e "$file_path" ]; then
    echo "school file exists"

    # Checking if the file is empty
    if [ -s "$file_path" ]; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi	
        
    # Checking if the file is a regular file
    if [ -f "$file_path" ]; then
	echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
