#!/usr/bin/env bash
# This script configures an Ubuntu server with specific IP address mappings in the /etc/hosts file.
cp /etc/hosts ~/hosts.bak
sed -i 's/^127.0.0.1/127.0.0.2/' ~/hosts.bak
echo '8.8.8.8 facebook.com' >> ~/hosts.bak
cp -f ~/hosts.bak /etc/hosts
