#!/usr/bin/env bash
# Configures Nginx to run as the www-data user

pkill apache2
chown www-data:www-data /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i 's/user\s*nginx;/user nginx nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen\s*80;/listen 8080;/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
